<?php
/**
 * Copyright © 2015 ebizmarts. All rights reserved.
 * See LICENSE.txt for license details.
 */

$_code = $block->getMethodCode();
$_config = $this->helper('Ebizmarts\SagePaySuite\Helper\Data')->getSagePayConfig();

?>


<div id="payment_form_<?php echo $_code ?>" class="admin__page-section-item" style="display:none;"
    data-mage-init='{"sagepaysuitepiCcForm":{
                            "url": {
                                "generateMerchantKey":"<?php echo $this->getUrl('sagepaysuite/pi/generateMerchantKey', []); ?>",
                                "request":"<?php echo $this->getUrl('sagepaysuite/pi/request', []); ?>"
                            },
                            "mode":"<?php echo $_config->getMode(); ?>"
                        }
                    }'>

    <span id="<?php echo $_code ?>-payment-errors" class="message error" style="display: none;"></span>

    <fieldset class="admin__fieldset">
    <div class="admin__field">
        <label class="label admin__field-label" for="<?php echo $_code ?>_cc_type" ><?php echo __('Credit Card Type') ?><span class="required">*</span></label>
        <div class="admin__field-control control">
            <select id="<?php echo $_code ?>_cc_type" class="required-entry _required select admin__control-select validate-cc-type-select">
                <option value="">--<?php echo __('Please Select')?>--</option>
            <?php $_ccType = $block->getInfoData('cc_type') ?>
            <?php foreach ($block->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </div>
    </fieldset>
    <fieldset class="admin__fieldset">
    <div class="admin__field">
        <label class="label admin__field-label" for="<?php echo $_code ?>_cc_number"><?php echo __('Credit Card Number') ?><span class="required">*</span></label>
        <div class="admin__field-control control">
            <input type="text" id="<?php echo $_code ?>_cc_number" title="<?php echo __('Credit Card Number') ?>" class="input-text admin__control-text validate-cc-number validate-cc-type" value="" />
        </div>
    </div>
    </fieldset>
    <fieldset class="admin__fieldset">
    <div id="<?php echo $_code ?>_cc_type_exp_div" class="admin__field">
        <label class="label admin__field-label" for="<?php echo $_code ?>_expiration" ><?php echo __('Expiration Date') ?><span class="required">*</span></label>
        <div class="admin__field-control control">
            <select id="<?php echo $_code ?>_expiration" class="month validate-cc-exp required-entry _required select admin__control-select">
            <?php $_ccExpMonth = $block->getInfoData('cc_exp_month') ?>
            <?php foreach ($block->getCcMonths() as $k=>$v): ?>
                <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
            <?php endforeach ?>
            </select>
            <?php $_ccExpYear = $block->getInfoData('cc_exp_year') ?>
            <select id="<?php echo $_code ?>_expiration_yr" class="year required-entry _required select admin__control-select">
            <?php foreach ($block->getCcYears() as $k=>$v): ?>
                <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </div>
    </fieldset>

    <?php if($block->hasVerification()): ?>
    <fieldset class="admin__fieldset hide_if_token_selected">
        <div id="<?php echo $_code ?>_cc_type_cvv_div" class="admin__field">
            <label class="label admin__field-label" for="<?php echo $_code ?>_cc_cid" ><?php echo __('Card Verification Number') ?><span class="required">*</span></label>
            <div class="admin__field-control control">
                <div class="v-fix">
                    <input type="text" title="<?php echo __('Card Verification Number') ?>" class="input-text cvv required-entry" id="<?php echo $_code ?>_cc_cid" value="" />
                </div>
            </div>
        </div>
    </fieldset>
    <?php endif; ?>
</div>