version: 2.1

orbs:
  sagepay: pruebas/ebizmarts-sagepay@0.0.4

executors:
  my-executor:
    docker:
      - image: circleci/php:7.1
    environment:
      PHP_UNIT_VERSION: 6.2
      SNIFFER_SEVERITY: 10
      SNIFFER_VERSION: v5
      MAGENTO_PATH: /home/circleci/magento2
      MAGENTO_VERSION: 226EE
      MAGENTO_VERSION_2210: 2210EE
      MAGENTO_WEB_SERVER_CONF: https://gist.githubusercontent.com/bcerban/25f3a2d93c19dc562020e0197f78685c/raw/70f1f314ad8ba5d302b911fe622a57ccec60a868/magento2.conf
      MAGENTO_COMPOSER_AUTH: https://gist.githubusercontent.com/centerax/5e42abec89d62a1308ba/raw/4b3242361c0690e234266afb3520c2940ac1055a/auth.json
      LIBSODIUM_VERSION: 1.0.18
    working_directory: ~/

jobs:
    DownloadTools226EE:
      executor: my-executor
      steps:
        - sagepay/download-pre-compiled-magento:
            version: $MAGENTO_VERSION
        - sagepay/download-tools:
            version: $MAGENTO_VERSION
        - persist_to_workspace:
            root: /home/circleci
            paths:
              - ./
    DownloadTools2210EE:
      executor: my-executor
      steps:
        - sagepay/download-pre-compiled-magento:
            version: $MAGENTO_VERSION_2210
        - sagepay/download-tools:
            version: $MAGENTO_VERSION_2210
        - persist_to_workspace:
            root: /home/circleci
            paths:
              - ./
    PHP 71 Code Sniffer:
      docker:
        - image: circleci/php:7.1-apache
      executor: my-executor
      steps:
        - attach_workspace:
            at: ~/magento2
        - sagepay/run-php-cs
    PHP 71 Unit Tests:
      docker:
        - image: circleci/php:7.1-apache
      executor: my-executor
      steps:
        - attach_workspace:
            at: ~/magento2
        - sagepay/run-php-unit-tests
    PHP 71 Compile and API test:
      docker:
        - image: ebizmarts/magento2-php71:0.0.1
        - image: circleci/mysql:5.6
          environment:
            MYSQL_USER: magento
            MYSQL_PASSWORD: magento
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: circle_test
            MYSQL_ALLOW_EMPTY_PASSWORD: true
      executor: my-executor
      steps:
        - attach_workspace:
            at: ~/magento2
        - sagepay/install-mariadb-and-setup-webserver
        - sagepay/magento-compile-and-setup-upgrade
        - sagepay/run-api-functional-tests
    PHP 71 unit tests with coverage:
      docker:
        - image: circleci/php:7.1-apache
      executor: my-executor
      steps:
        - attach_workspace:
            at: ~/magento2
        - sagepay/run-php-unit-tests:
            coverage: --coverage-text
    PHP 70 Code Sniffer:
      docker:
        - image: circleci/php:7.0-apache
      executor: my-executor
      steps:
        - attach_workspace:
            at: ~/magento2
        - sagepay/run-php-cs
    PHP 70 Unit Tests:
      docker:
        - image: circleci/php:7.0-apache
      executor: my-executor
      steps:
        - attach_workspace:
            at: ~/magento2
        - sagepay/run-php-unit-tests
    PHP 70 Compile and API test:
      docker:
        - image: ebizmarts/magento2-php70:0.0.1
        - image: circleci/mysql:5.6
          environment:
            MYSQL_USER: magento
            MYSQL_PASSWORD: magento
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: circle_test
            MYSQL_ALLOW_EMPTY_PASSWORD: true
      executor: my-executor
      steps:
        - attach_workspace:
            at: ~/magento2
        - run: sudo sh -c 'echo "199.188.207.57 test.sagepay.com pi-test.sagepay.com" >> /etc/hosts'
        - sagepay/install-mariadb-and-setup-webserver
        - sagepay/magento-compile-and-setup-upgrade
        - run: $MAGENTO_PATH/bin/magento cache:enable
        - sagepay/run-api-functional-tests
    PHP 70 unit tests with coverage:
      docker:
        - image: circleci/php:7.0-apache
      executor: my-executor
      steps:
        - attach_workspace:
            at: ~/magento2
        - sagepay/run-php-unit-tests:
            coverage: --coverage-text
    PHP 72 Code Sniffer:
      docker:
        - image: circleci/php:7.2-apache
      executor: my-executor
      steps:
        - attach_workspace:
            at: ~/magento2
        - sagepay/run-php-cs
    PHP 72 Unit Tests:
      docker:
        - image: circleci/php:7.2-apache
      executor: my-executor
      steps:
        - attach_workspace:
            at: ~/magento2
        - sagepay/run-php-unit-tests
    PHP 72 Compile and API test:
      docker:
        - image: ebizmarts/magento2-php72:0.0.2
        - image: circleci/mysql:5.6
          environment:
            MYSQL_USER: magento
            MYSQL_PASSWORD: magento
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: circle_test
            MYSQL_ALLOW_EMPTY_PASSWORD: true
      executor: my-executor
      steps:
        - attach_workspace:
            at: ~/magento2
        - sagepay/install-mariadb-and-setup-webserver
        - sagepay/magento-compile-and-setup-upgrade
    PHP 72 unit tests with coverage:
      docker:
        - image: circleci/php:7.2-apache
      executor: my-executor
      steps:
        - attach_workspace:
            at: ~/magento2
        - sagepay/run-php-unit-tests:
            coverage: --coverage-text

workflows:
  version: 2.1
  build_test:
    jobs:
      - DownloadTools226EE
      #- DownloadTools2210EE
#      - PHP 70 Code Sniffer:
#          requires:
#            - DownloadTools226EE
#      - PHP 70 Unit Tests:
#          requires:
#            - PHP 70 Code Sniffer
      - PHP 70 Compile and API test:
          requires:
            - DownloadTools226EE
#      - PHP 70 unit tests with coverage:
#          requires:
#            - PHP 70 Compile and API test
#      - PHP 71 Code Sniffer:
#          requires:
#            - DownloadTools226EE
#      - PHP 71 Unit Tests:
#          requires:
#            - PHP 71 Code Sniffer
#      - PHP 71 Compile and API test:
#          requires:
#            - DownloadTools226EE
#      - PHP 71 unit tests with coverage:
#          requires:
#            - PHP 71 Compile and API test
#      - PHP 72 Code Sniffer:
#          requires:
#            - DownloadTools2210EE
#      - PHP 72 Unit Tests:
#          requires:
#            - PHP 72 Code Sniffer
#      - PHP 72 Compile and API test:
#          requires:
#            - PHP 72 Unit Tests
#      - PHP 72 unit tests with coverage:
#          requires:
#            - PHP 72 Compile and API test