<?php
/**
 * Copyright © 2015 eBizmarts. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \Ebizmarts\SagePaySuite\Block\Form\Form
 */
?>
<!-- SagePay Logo -->
<!--<img src="--><?php //echo $block->escapeHtml($block->getPaymentAcceptanceMarkSrc()) ?><!--"-->
<!--     alt="--><?php //echo __('Acceptance Mark') ?><!--" class="paypal icon"/>-->
<!--<a href="--><?php //echo $block->getPaymentAcceptanceMarkHref() ?><!--"-->
<!--   onclick="javascript:window.open('--><?php //echo $block->getPaymentAcceptanceMarkHref() ?><!--','olcwhatispaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,left=0, top=0, width=400, height=350'); return false;"-->
<!--   class="action paypal about">-->
<!--    --><?php //if ($block->getPaymentWhatIs()) {
//    echo __($block->getPaymentWhatIs());
//} else {
//    echo __('What is PayPal?');
//} ?>
<!--</a>-->



<img src="http://www.sagepay.co.uk/files/logo_0.png">
lalalala

<!-- SagePay Logo -->
