<?php
/**
 * Copyright © 2015 eBizmarts. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \Ebizmarts\SagePaySuite\Block\Form\Form
 **/
?>
<!--<fieldset class="fieldset sagepaysuite items redirect" id="payment_form_--><?php //echo $block->getMethodCode() ?><!--" style="display:none;">-->
<!--    <div>--><?php //echo $block->getRedirectMessage(); ?><!--</div>-->
<!---->


<!--    --><?php //$code = $block->getBillingAgreementCode(); ?>
<!--    --><?php //if ($code): ?>
<!--        <input type="checkbox" id="--><?php //echo $code ?><!--" value="1" name="payment[--><?php //echo $code ?><!--]" class="checkbox">-->
<!--        <label for="--><?php //echo $code ?><!--" class="label">-->
<!--            <span>--><?php //echo __('Sign a billing agreement to streamline further purchases with PayPal.') ?><!--</span>-->
<!--        </label>-->
<!--    --><?php //endif; ?>
lalalalooo
</fieldset>
