<style type="text/css">

    #sagepaysuite-version-container {
        background: #f8f8f8;
        border: 1px solid #e3e3e3;
        padding: 1.5rem;
    }

    #sagepaysuite-version-container img {
        width: 250px;
        margin-bottom: 10px;
    }

    #sagepaysuite-version-container h2 {
        color:#EA7601;
        font-weight: bold;
        margin-bottom: 5px;
    }

    #sagepaysuite-version-container p {
        font-size: 12px;
    }

</style>

<div id="sagepaysuite-version-container">
    <img src="https://ebizmarts.com/img/extension-logo/logo-extension-sagepay-retina.png"/>
    <h2>Ebizmarts Sage Pay Suite <?php echo $this->getVersion()?></h2>
    <p>
        <a target="_blank" href="https://ebizmarts.com"><b>ebizmarts</b></a> is a Sage Pay approved partner.
        <a target="_blank" href="https://www.engage.sagepay.com/sign-up-with-ebizmarts">Get a Sage Pay Account Now!</a>
    </p>
    <p>Need assistance?
        <a target="_blank" href="mailto:sagepay@ebizmarts.brippo.com">Submit a ticket</a>
    </p>
    <p>Got feedback?
        <a target="_blank" href="mailto:info@ebizmarts.com">Email us</a> or
        <a target="_blank" href="http://store.ebizmarts.com/subscribe-to-our-newsletter">Subscribe to our newsletter</a>
    </p>
</div>